---

- name: install packages

  become: true

  package: >-
    name={{ item }}
    state=present

  with_items:
    - git

    - make
    - gcc
    - g++
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - zlib1g-dev


  tags: [ packages ]
